CREATE TABLE IF NOT EXISTS ANDY_INFORMATION(
	ID INT NOT NULL,
    IMAGE BLOB NOT NULL,
	NAME CHAR(32) NOT NULL,
	AGE INT NULL,
	POSITION CHAR(32) NULL,
    PRIMARY KEY (ID)
) DEFAULT CHARSET=utf8;


CREATE INDEX INDEX_INFO ON ANDY_INFORMATION(NAME);
CREATE INDEX INDEX_ID ON ANDY_INFORMATION(ID);
